# This file is used by the "webots-test-sources-master" and "webots-test-sources-develop" appveyor projects.

clone_depth: 1

install:
  - set PATH=C:\Python38-x64;C:\Python38-x64\Scripts;C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%
  # The following line is needed to work around a bug in MSYS2 pacman, it should be removed when fixed.
  # See: https://github.com/msys2/MSYS2-packages/issues/1967
  - pacman -U --noconfirm pacman --noconfirm -U http://repo.msys2.org/msys/x86_64/pacman-5.2.1-6-x86_64.pkg.tar.xz
  - pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  - pacman --noconfirm -Syuu
  - pacman --noconfirm -S mingw-w64-x86_64-cppcheck
  - pacman --noconfirm -S mingw-w64-x86_64-clang
  - pip install -r %APPVEYOR_BUILD_FOLDER%\\tests\\sources\\requirements.txt
  - pip install -r %APPVEYOR_BUILD_FOLDER%\\docs\\tests\\requirements.txt
  - copy %APPVEYOR_BUILD_FOLDER%\\dependencies\\.clang-format-9 %APPVEYOR_BUILD_FOLDER%\\.clang-format

build: off

test_script:
  - set WEBOTS_HOME=%APPVEYOR_BUILD_FOLDER%
  - python -m unittest discover -s %APPVEYOR_BUILD_FOLDER%\\docs\\tests
  - python -m unittest discover -s %APPVEYOR_BUILD_FOLDER%\\tests\\sources
